title: Franck Verrot
email: franck@verrot.fr
description: >
  Software Craftsman, Journey Man, Open Source Enthusiast
baseurl: ""
url: "http://franck.verrot.fr"
twitter_username: franckverrot
github_username:  franckverrot
permalink: /blog/:year/:month/:day/:title
markdown: kramdown
